# Generated by Django 2.1.2 on 2018-10-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20181025_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriecounter',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caloriecounter',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ts'),
        ),
    ]
