# Generated by Django 2.1.2 on 2018-10-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_auto_20181025_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calories',
            old_name='user_id',
            new_name='user',
        ),
    ]
