# Generated by Django 2.1.3 on 2018-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0006_auto_20181104_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='calories',
            name='servings',
            field=models.FloatField(blank=True, null=True, verbose_name='servings'),
        ),
    ]
