# Generated by Django 2.1.3 on 2018-11-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0007_calories_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='food_name',
            field=models.CharField(default='Food', max_length=32, verbose_name='name'),
        ),
    ]
